spring:
  devtools:
    restart:
      enabled: ${DEVTOOL_ENABLED:false}
      poll-interval: 2s
      quiet-period: 1s
dev:
  advice:
    show-line-numbers: ${DEV_ADVICE_SHOW_LINE_NUMBERS:true}
    show-stack-trace: ${DEV_ADVICE_SHOW_STACK_TRACE:true}
    debug-console: ${DEV_ADVICE_DEBUG_CONSOLE:true}
